name: book_bridge
description: "A peer-to-peer marketplace for Cameroonian students to buy and sell used physical books."
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.10.7

dependencies:
  dartz: ^0.10.1
  equatable: ^2.0.8
  flutter:
    sdk: flutter
  get_it: ^9.2.0
  go_router: ^17.0.1
  image_picker: ^1.2.1
  intl: ^0.20.2
  provider: ^6.1.5+1
  supabase_flutter: ^2.12.0
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
